### ISSUE TITLE
ClassCastException in VertexToTuple2Map

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#41]
I got the following exception when trying to run a PageRank experiment on a cluster [(source code)] (https://github.com/vasia/flink-graph/blob/d71ddca8ce0dbf8ee60f3c69c1b82b77eb6a7359/src/main/java/flink/graphs/experiments/PageRankExperiment.java):

org.apache.flink.client.program.ProgramInvocationException: The program execution failed: java.lang.ClassCastException: org.apache.flink.api.java.tuple.Tuple2 cannot be cast to flink.graphs.Vertex
	at flink.graphs.utils.VertexToTuple2Map.map(VertexToTuple2Map.java:10)
	at org.apache.flink.runtime.operators.MapDriver.run(MapDriver.java:84)
	at org.apache.flink.runtime.operators.RegularPactTask.run(RegularPactTask.java:493)
	at org.apache.flink.runtime.operators.RegularPactTask.invoke(RegularPactTask.java:360)
	at org.apache.flink.runtime.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:257)
	at java.lang.Thread.run(Thread.java:744)
	at org.apache.flink.client.program.Client.run(Client.java:328)
	at org.apache.flink.client.program.Client.run(Client.java:294)
	at org.apache.flink.client.program.Client.run(Client.java:288)
	at org.apache.flink.client.program.ContextEnvironment.execute(ContextEnvironment.java:55)
	at org.apache.flink.api.java.ExecutionEnvironment.execute(ExecutionEnvironment.java:619)
	at flink.graphs.experiments.PageRankExperiment.main(PageRankExperiment.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:434)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:350)
	at org.apache.flink.client.program.Client.run(Client.java:240)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:343)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:330)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:983)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1007)

**Comment by vasia** [comment]
Hi,

I ran into another ClassCastException, for [this PageRank code] (https://github.com/vasia/flink-graph/blob/experiments/src/main/java/flink/graphs/experiments/PageRankTypeException.java):
```
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: java.lang.ClassCastException: org.apache.flink.api.java.tuple.Tuple2 cannot be cast to flink.graphs.Vertex
	at flink.graphs.Graph$CountNeighborsCoGroup.coGroup(Graph.java:329)
	at org.apache.flink.runtime.operators.CoGroupDriver.run(CoGroupDriver.java:130)
	at org.apache.flink.runtime.operators.RegularPactTask.run(RegularPactTask.java:495)
	at org.apache.flink.runtime.operators.RegularPactTask.invoke(RegularPactTask.java:362)
	at org.apache.flink.runtime.execution.RuntimeEnvironment.run(RuntimeEnvironment.java:257)
	at java.lang.Thread.run(Thread.java:745)
```
Stephan's trick fixes both cases, but I don't really understand why this error appears and where this cast is coming from.

**Comment by StephanEwen** [comment]
I think the reason is the following:

Since Java erases the types of the records in the data sets, the runtime would not know that the type is a `Vertex` or a `Tuple2<Long, Double>`. To have this information at runtime, the data set maintains its own type info, which is in some way like Scala's Class Tags or Type Manifests.

I assume that some casts make a produced data set a `DataSet<Vertex>`, while the internal type info marks it as a set of Tuple2. Then, the result elements will be serialized as `Tuple2<Long, Double>`, even if they are actually of type `Vertex`.

Can you check if such casting occurs somewhere?

**Comment by vasia** [comment]
I think the problem is that both in `create` in my example and in `mapVertices` in @balidani's case, `getProducedType()` returns a `TupleTypeInfo`, so the produced vertices DataSet has an internal Tuple2 type. Then, when the coGroup is called on the vertex DataSet, the given input type is Vertex, while the internal is Tuple2.
So, I guess, instead of returning a `TupleTypeInfo`, we should somehow correctly create and return the Vertex type.. How could we do that?

**Comment by StephanEwen** [comment]
Since Vertex is a tuple type, you can use the TupleTypeInfo and give it the Vertex class as the class type:
```java
TupleTypeInfo<Vertex> vType = new TupleTypeInfo<Vertex>(Vertex.class, type1, type2, type3);
```

**Comment by StephanEwen** [comment]
That should do the trick...

**Comment by vasia** [comment]
Indeed :-) Thanks @StephanEwen ^^
@balidani, I'll push this fin in a while and let you know to continue with your example.
