### ISSUE TITLE
Type issues with mapVertices

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#46]
Hello everyone,

after [removing the `keyType`, `vertexValueType` static fields from the `Graph` class](https://github.com/project-flink/flink-graph/commit/d26445f0fbf346dad9464e08554d3279f1cdb4cc) ,
the `SingleSourceShortestPaths` example fails with the following exception:

```
Exception in thread "main" org.apache.flink.api.common.functions.InvalidTypesException: Type of TypeVariable 'K' in 'class flink.graphs.library.SingleSourceShortestPaths$InitVerticesMapper' could not be determined. This is most likely a type erasure problem. The type extraction currently supports types with generic variables only in cases where all variables in the return type can be deduced from the input type(s).
	at org.apache.flink.api.java.typeutils.TypeExtractor.createTypeInfoWithTypeHierarchy(TypeExtractor.java:288)
	at org.apache.flink.api.java.typeutils.TypeExtractor.privateCreateTypeInfo(TypeExtractor.java:223)
	at org.apache.flink.api.java.typeutils.TypeExtractor.createTypeInfo(TypeExtractor.java:193)
	at flink.graphs.Graph$ApplyMapperToVertexWithType.getProducedType(Graph.java:129)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:149)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getMapReturnTypes(TypeExtractor.java:78)
	at org.apache.flink.api.java.DataSet.map(DataSet.java:160)
	at flink.graphs.Graph.mapVertices(Graph.java:109)
	at flink.graphs.library.SingleSourceShortestPaths.run(SingleSourceShortestPaths.java:27)
	at flink.graphs.Graph.run(Graph.java:1001)
	at flink.graphs.example.SingleSourceShortestPathsExample.main(SingleSourceShortestPathsExample.java:30)
```

I tried retrieving the key type inside `mapVertices` using `TypeInformation<K> keyType = ((TupleTypeInfo<?>) vertices.getType()).getTypeAt(0)` and then passing it to `ApplyMapperToVertexWithType` as a parameter, but this leads to the following:

```
Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: Task flink.graphs.Graph$ApplyMapperToVertexWithType@32535e27 not serializable: 
	at org.apache.flink.api.java.ClosureCleaner.ensureSerializable(ClosureCleaner.java:97)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:59)
	at org.apache.flink.api.java.DataSet.clean(DataSet.java:133)
	at org.apache.flink.api.java.DataSet.map(DataSet.java:162)
	at flink.graphs.Graph.mapVertices(Graph.java:110)
	at flink.graphs.library.SingleSourceShortestPaths.run(SingleSourceShortestPaths.java:27)
	at flink.graphs.Graph.run(Graph.java:1008)
	at flink.graphs.example.SingleSourceShortestPathsExample.main(SingleSourceShortestPathsExample.java:30)
Caused by: java.io.NotSerializableException: org.apache.flink.api.common.typeinfo.BasicTypeInfo
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:286)
	at org.apache.flink.api.java.ClosureCleaner.ensureSerializable(ClosureCleaner.java:95)
	... 7 more
```

Any suggestions?
Thanks!

**Comment by StephanEwen** [comment]
It seems that the type info becomes a variable in the class and thus part
of the data that needs to be serialized. Since the type info is not
serializable, this must fail.

You can solve this by making the field transient, or by not having such a
field at all, but lazily extract the type in the "getReturnType()" or
"getProducedType()" method.

**Comment by vasia** [comment]
Currently, I'm using `TypeExtractor.createTypeInfo` inside `getReturnType` to get the key type, but this gives the first exception. Is this what you mean by "lazily extract the type"?
Making the field transient seems to work :)
