### ISSUE TITLE
Creating a graph using a mapper function does not work

### ISSUE THREAD

**Issue by cebe** [project-flink/flink-graph#65]
Simple Job:

```java
package de.tu_berlin.impro3.flink.etl;

import flink.graphs.Edge;
import flink.graphs.Graph;
import flink.graphs.utils.GraphUtils;
import org.apache.flink.api.common.functions.MapFunction;
import org.apache.flink.api.java.DataSet;
import org.apache.flink.api.java.ExecutionEnvironment;
import org.apache.flink.types.NullValue;

public class Bugreport {

    public static void main(String[] args) throws Exception {

        final ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();

        // read edges from file
        DataSet<Edge<Long, NullValue>> edges = GraphUtils.readEdgesFromCsvFile(env, "/tmp/flink/test.txt", ' ', Long.class);

        // create graph, initialize vertex values with false = not visited
        Graph<Long, Boolean, NullValue> graph = Graph.fromDataSet(edges, new MapFunction<Long, Boolean>() {

            @Override
            public Boolean map(Long value) throws Exception {
                return false;
            }
        }, env);

        env.execute("Graph Subsampling Random Walk");
    }
}
```

Run it:

```
$ ./flink run -c de.tu_berlin.impro3.flink.etl.Bugreport -v /home/cebe/Dokumente/Uni/impro/IMPRO-3.WS14/impro3-ws14-flink/target/impro3-ws14-flink-1.0-SNAPSHOT.jar /tmp/flink/test.txt /tmp/flink/out.txt
Error: The main method caused an error.
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:449)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:350)
	at org.apache.flink.client.program.Client.run(Client.java:242)
	at org.apache.flink.client.CliFrontend.executeProgram(CliFrontend.java:349)
	at org.apache.flink.client.CliFrontend.run(CliFrontend.java:336)
	at org.apache.flink.client.CliFrontend.parseParameters(CliFrontend.java:976)
	at org.apache.flink.client.CliFrontend.main(CliFrontend.java:1000)
Caused by: org.apache.flink.api.common.functions.InvalidTypesException: Type of TypeVariable 'VV' in 'public static flink.graphs.Graph flink.graphs.Graph.fromDataSet(org.apache.flink.api.java.DataSet,org.apache.flink.api.common.functions.MapFunction,org.apache.flink.api.java.ExecutionEnvironment)' could not be determined. This is most likely a type erasure problem. The type extraction currently supports types with generic variables only in cases where all variables in the return type can be deduced from the input type(s).
	at org.apache.flink.api.java.typeutils.TypeExtractor.createTypeInfoWithTypeHierarchy(TypeExtractor.java:288)
	at org.apache.flink.api.java.typeutils.TypeExtractor.privateCreateTypeInfo(TypeExtractor.java:223)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:151)
	at org.apache.flink.api.java.typeutils.TypeExtractor.getMapReturnTypes(TypeExtractor.java:78)
	at org.apache.flink.api.java.DataSet.map(DataSet.java:160)
	at flink.graphs.Graph.fromDataSet(Graph.java:201)
	at de.tu_berlin.impro3.flink.etl.Bugreport.main(Bugreport.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:434)
	... 6 more
```

I am using the current master i.e. https://github.com/project-flink/flink-graph/commit/b541d096379b04e027ac4df3f52944428ec8f733

**Comment by vasia** [comment]
Hi @cebe! 
I see you're using `readEdgesFromCsvFile` (which is not merged). Have you tested this?
I tried reproducing your error, but reading the edges like this:

```
DataSet<Edge<Long, NullValue>> edges = env.readCsvFile(args[0]).lineDelimiter("\n").fieldDelimiter('\t')
				.types(Long.class, Long.class).map(new MapFunction<Tuple2<Long, Long>, Edge<Long, NullValue>>() {
					public Edge<Long, NullValue> map(Tuple2<Long, Long> value) {
						return new Edge<Long, NullValue>(value.f0, value.f1, NullValue.getInstance());
					}
				});
```

The above runs without problem.

**Comment by cebe** [comment]
kind of related to this: https://github.com/project-flink/flink-graph/commit/b541d096379b04e027ac4df3f52944428ec8f733#commitcomment-9375070

Will do some tests about this.
